#!/usr/bin/env bash
set -x -e -u -o pipefail

mkdir _build

pushd cmd/cot
build_cot() {
    GOOS="$1" GOARCH="$2" go build -ldflags '-s -w' -o "$3"
    chmod +x "$3"
}
build_cot linux  amd64 ../../_build/cot_linux_amd64
popd
