#!/usr/bin/env bash
set -x -e -u -o pipefail

mkdir _build

pushd cmd/cot
build_cot() {
    GOOS="$1" GOARCH="$2" go build -ldflags '-s -w' -o "${3}/cot_${1}_${2}"
    chmod +x "$3"
}
build_cot linux  amd64 ../../_build
build_cot darwin amd64 ../../_build
popd
