on: push
name: Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        uses: ./.ci
        with:
          args: /test

      - name: Build
        uses: ./.ci
        with:
          args: /build

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_COMPRESS: gz
          GHR_PATH: _build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.event.ref, 'refs/tags/')
